from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import io

def generate_report_pdf(report: dict, location_name: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, 
                           topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    styles = getSampleStyleSheet()
    elements = []

    risk_colors = {
        "LOW": "#22c55e", "MODERATE": "#f59e0b",
        "HIGH": "#ef4444", "CRITICAL": "#7c3aed"
    }
    risk_color = HexColor(risk_colors.get(report.get("risk_level", "LOW"), "#22c55e"))

    # Header
    elements.append(Paragraph(
        '<font color="#1a73e8" size="24"><b>Watershed</b></font> '
        '<font color="#666" size="12">Water Safety AI</font>',
        styles['Title']
    ))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(
        f'<font color="#333" size="14"><b>Water Safety Report: {location_name}</b></font>',
        styles['Normal']
    ))
    elements.append(Spacer(1, 0.2*inch))

    # Risk score box
    risk_data = [[
        f'RISK LEVEL: {report.get("risk_level")}',
        f'SCORE: {report.get("risk_score")}/100'
    ]]
    risk_table = Table(risk_data, colWidths=[3*inch, 3*inch])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), risk_color),
        ('TEXTCOLOR', (0,0), (-1,-1), white),
        ('FONTSIZE', (0,0), (-1,-1), 14),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('PADDING', (0,0), (-1,-1), 12),
        ('ROUNDEDCORNERS', [8,8,8,8]),
    ]))
    elements.append(risk_table)
    elements.append(Spacer(1, 0.2*inch))

    # Headline
    elements.append(Paragraph(f'<b>{report.get("headline", "")}</b>', styles['Heading2']))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(report.get("summary", ""), styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))

    # Key findings
    elements.append(Paragraph('<b>KEY FINDINGS</b>', styles['Heading3']))
    for finding in report.get("key_findings", []):
        elements.append(Paragraph(f'• {finding}', styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))

    # Primary threat
    elements.append(Paragraph('<b>PRIMARY THREAT</b>', styles['Heading3']))
    elements.append(Paragraph(report.get("primary_threat", ""), styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))

    # Recommended actions
    elements.append(Paragraph('<b>RECOMMENDED ACTIONS</b>', styles['Heading3']))
    for i, action in enumerate(report.get("recommended_actions", []), 1):
        elements.append(Paragraph(f'{i}. {action}', styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))

    # Footer
    elements.append(Paragraph(
        '<font color="#999" size="8">Generated by Watershed AI — '
        'Data sources: USGS/NASA Live Water Monitor + EPA ATTAINS</font>',
        styles['Normal']
    ))

    doc.build(elements)
    return buffer.getvalue()
